import { Contribuyente } from './contribuyente';
import { Moneda } from './moneda';
import { DetalleCPE } from './detalle-cpe';
import { DatoAdicional } from './dato-adicional';
import { DatosGuia } from './datos-guia';
import { DocumentoRelacionado } from './documento-relacionado';
import { Discrepancia } from './discrepancia';
export declare class CPE {
    ublVersion?: string;
    tipoOperacion?: string;
    tipoDocumento?: string;
    serie?: string;
    correlativo?: string;
    empresa?: Contribuyente;
    cliente?: Contribuyente;
    fechaEmision?: Date;
    fechaVencimiento?: Date;
    moneda?: Moneda;
    catImpuesto?: string;
    pjeImpuesto?: number;
    gravadas?: number;
    gratuitas?: number;
    inafectas?: number;
    exoneradas?: number;
    descuentoGlobal?: number;
    items?: DetalleCPE[];
    subTotal?: number;
    totalVenta?: number;
    totalIgv?: number;
    totalIsc?: number;
    totalOtrosTributos?: number;
    totalOtrosCargos?: number;
    montoLetras?: string;
    placaVehiculo?: string;
    montoPercepcion?: number;
    montoDetraccion?: number;
    datosAdicionales?: DatoAdicional[];
    tipoDocAnticipo?: string;
    docAnticipo?: string;
    monedaAnticipo?: string;
    montoAnticipo?: number;
    datosGuiaTransportista?: DatosGuia;
    relacionados?: DocumentoRelacionado[];
    otrosDocumentosRelacionados?: DocumentoRelacionado[];
    discrepancias?: Discrepancia[];
    nroOrdenCompra?: string;
    calculoIgv: number;
    calculoIsc: number;
    calculoDetraccion: number;
    private _comprobante?;
    constructor(documento?: any);
    get comprobante(): string;
    fileName(): string;
}
