export var DocumentType;
(function (DocumentType) {
    DocumentType["FACTURA"] = "01";
    DocumentType["BOLETA DE VENTA"] = "03";
    DocumentType["NOTA DE CREDITO"] = "07";
    DocumentType["NOTA DE DEBITO"] = "08";
    DocumentType["GUIA DE REMISI\u00D3N REMITENTE"] = "09";
    DocumentType["TICKET DE MAQUINA REGISTRADORA"] = "12";
    DocumentType["DOCUMENTO EMITIDO POR BANCOS, INSTITUCIONES FINANCIERAS, CREDITICIAS Y DE SEGUROS QUE SE ENCUENTREN BAJO EL CONTROL DE LA SUPERINTENDENCIA DE BANCA Y SEGUROS"] = "13";
    DocumentType["RECIBO SERVICIOS PUBLICOS"] = "14";
    DocumentType["BOLETO DE VIAJE EMITIDO POR LAS EMPRESAS DE TRANSPORTE P\u00DABLICO INTERPROVINCIAL DE PASAJEROS"] = "16";
    DocumentType["DOCUMENTOS EMITIDOS POR LAS AFP"] = "18";
    DocumentType["COMPROBANTE DE RETENCION"] = "20";
    DocumentType["GUIA DE REMISI\u00D3N TRANSPORTISTA"] = "31";
    DocumentType["COMPROBANTE DE PERCEPCION"] = "40";
    DocumentType["COMPROBANTE DE PERCEPCION \u2013 VENTA INTERNA (F\u00CDSICO-FORMATO IMPRESO"] = "41";
    DocumentType["COMPROBANTE DE PAGO SEAE"] = "56";
    DocumentType["GUIA DE REMISI\u00D3N REMITENTE COMPLEMENTARIA"] = "71";
    DocumentType["GUIA DE REMISION TRANSPORTISTA COMPLEMENTARIA"] = "72";
})(DocumentType || (DocumentType = {}));
;
//# sourceMappingURL=document-type.js.map