export declare const Namespaces: {
    xmlnsInvoice: string;
    xmlnsCreditNote: string;
    xmlnsDebitNote: string;
    xmlnsVoidedDocuments: string;
    xmlnsSummaryDocuments: string;
    xmlnsRetention: string;
    xmlnsPerception: string;
    xmlnsDespatchAdvice: string;
    sac: string;
    cac: string;
    cbc: string;
    udt: string;
    ccts: string;
    ext: string;
    qdt: string;
    ds: string;
    xsi: string;
    ar: string;
    wssecurity: string;
    nodoId: string;
    nodoResponseDate: string;
    nodoResponseTime: string;
    nodoResponseCode: string;
    nodoDescription: string;
};
